# 2019-03-24 (cc) <paul4hough@gmail.com>
#
---
groups:
- name: service
  rules:
  - record: fed:node_systemd_unit_state
    expr: max_over_time(node_systemd_unit_state[1h])
  - alert: service
    expr: node_systemd_unit_state{state="failed"} > 0
